# Generated by Django 4.0.3 on 2022-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiaryuser',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
